### ISSUE TITLE
Minimizing app and clicking dock icon doesn't restore

### ISSUE THREAD

**Issue by boxingfan123** [kean/PulsePro#24] opened 2022-05-25 16:53 UTC
I noticed that when you minimize PulsePro, and then click on its icon in the dock bar, it doesn't restore. By "icon in the dock bar" I'm not talking about the window preview, but the actual app icon.

I also tested this with a brand new SwiftUI macOS app, and the same behavior appears.

However, I think there is a workaround [here](https://github.com/writefreely/writefreely-swiftui-multiplatform/issues/135).

**Comment by kean** [comment] 2022-09-30 23:30
I tested it on the latest Ventura beta and can't reproduce it. I hope it's fixed on the platform level.

**Closed by kean** 2022-09-30 23:30 UTC
